### ISSUE TITLE
non standard date separaters

### ISSUE THREAD

**Issue by shaneknysh** [todotxt/language-todotxt#58]
I use . as a date separator I've forked and modified the code to meet my needs. Do you think there is a big enough audience to add this to the options and allow user to select the data separator?

**Comment by inkarkat** [comment]
The [specification](https://github.com/todotxt/todo.txt#rule-2-a-tasks-creation-date-may-optionally-appear-directly-after-priority-and-a-space) says:

> If the creation date exists, it should be in the format `YYYY-MM-DD`.

If you refer to `todo.txt-cli` for your local modifications, that surely is possible. I'm against a configuration option for this, first because the spec does not recommend / allow this, and second because several add-ons would not understand this format and would have to be updated (which will never fully happen, as some authors have abandoned their add-on).

**Comment by shaneknysh** [comment]
I've made the local modifications but I did not think they would be popular enough to justify the addition into the main repo. I didn't want to go any further building a setting and requesting a pull request if I am the only one who would use the feature. 

I'll keep my changes in my fork and close this issue.
