### ISSUE TITLE
Interferes with Markdown Preview (core package)

### ISSUE THREAD

**Issue by izaakm** [todotxt/language-todotxt#7]
With this package installed, I'm not able to open a Markdown preview. Has anyone else had this problem?

I'm not sure if this is the right place to report this. 
- Atom 1.10.2
- language-todotxt 0.6.1
- OSX 10.11.6

Let me know if there's anything I can do to help resolve this issue.

**Comment by evanp** [comment]
@izaakm I think I see what's going on here. If you have a Markdown file that ends in .txt it won't work, because language-todotxt tries to load for all .txt files. The new 1.0.0 version only loads for todo.txt, so this should be fixed.

Let me know if you see the problem again after 1.0.0 is released.
